### PR TITLE
cleanup example app

### PR DESCRIPTION
**Pull request by qinfchen**
- use slash for ng route mapping
- always redirect to the "/"

### CODE REVIEW

**Comment by jmcampanini** [comment]
:-1: the example app only ever loads the "Hello World" page. you need to turn on the html5 mode:

https://scotch.io/tutorials/pretty-urls-in-angularjs-removing-the-hashtag

**Comment by jmcampanini** [comment]
does this need to be rebased?

**Comment by qinfchen** [comment]
html5 mode is needed. :(

**Comment by jmcampanini** [comment]
:+1:

**Pull request merged**
